### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by k1ic** [Caldis/react-zmage#141]
ReferenceError: window is not defined
    at /home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:350:2
    at /home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:339:46
    at module.exports.../../../DropboxMapping/Dev/react-zmage/node_modules/style-loader/lib/addStyles.js.module.exports (/home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:407:88)
    at Object../src/components/Browser/Browser.less (/home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:888:218)
    at __webpack_require__ (/home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:21:30)
    at Module../src/index.js (/home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:1022:23)
    at __webpack_require__ (/home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:21:30)
    at /home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:85:18
    at Object.<anonymous> (/home/forge/mengyangnews/node_modules/react-zmage/lib/zmage.development.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/forge/mengyangnews/node_modules/react-zmage/lib/index.js:6:22)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)

**Comment by Eline2017** [comment]
你试试在webpack.config.js文件里面配置一下
![image](https://user-images.githubusercontent.com/23447167/81157923-0d6a9800-8fba-11ea-8299-0208bbee80e0.png) 其次看看是不是使用了next.js,ssr 需要设置为非服务器渲染。
![image](https://user-images.githubusercontent.com/23447167/81158081-3428ce80-8fba-11ea-8544-acff07d641cc.png)

**Comment by k1ic** [comment]
@Eline2017 收到，多谢
